services:
  ecommerce_mysql_db:
    container_name: ecommerce-db
    image: mysql
    command: --default-authentication-plugin=mysql_native_password
    environment:
      MYSQL_DATABASE: waafinalproject
      MYSQL_ROOT_PASSWORD: testd
    ports:
      - "3306:3306"
    restart: unless-stopped